
#define IDM_TOOL    2
#define IDM_STATUS  3
#define ID_DLG_CAR  4
#define ID_dlg_ANI  5
#define ID_dlg_SND  6
#define IDR_MENU    7
#define IDF_NEW     8
#define IDF_OPEN    9
#define IDF_SAVEAS  10
#define IDF_EXIT    11
#define IDF_IMTEX   12
#define IDF_EXTEX   13
#define IDF_IMMOD   14
#define IDF_EXMOD   15
#define IDF_ANI     16
#define IDF_SND     17
#define IDF_ABOUT   18
#define IDF_HELP    19
#define IDF_LIGHT   20
#define IDF_FLAGS   21
#define IDF_WIRE    22
#define IDB_OK      23
#define IDB_CLOSE   24
#define IDB_OPEN    25
#define IDB_SAVE    26
#define IDB_NEXT    27
#define IDB_PREV        28
#define IDB_SPLAY       29
#define IDB_APLAY       30
#define IDB_ASTOP       31
#define ID_NAME         32
#define ID_AKPS         33
#define ID_ATIME        34
#define ID_AFRM         35
#define ID_SIZE         36
#define ID_TB_IMAGE     37
#define ID_ANIM_PLAY    38
#define ID_ANIM_PAUSE   39
#define ID_ANIM_STOP    40
#define ID_UPLOAD       41
#define IDF_PROPERTIES  42
#define ID_O_RADIUS     43
#define ID_O_YLO        44
#define ID_O_YHI        45
#define ID_O_BOUNDR     46
#define IDV_BONES       47
#define IDV_JOINTS      48
#define IDF_UPDATE      49
#define IDV_PERSPECTIVE 50
//
#define IDV_GRID		57
#define ID_ABOUT_DIALOG 58
#define ID_ABOUT_OK		59
#define ID_ABOUT_TEXT	60
#define ID_ABOUT_IMG	61
#define IDV_AXIS		62
#define	IDV_FIRSTPERSON	63


#define IDT_FLIPTRIS    68

#define IDC_FLAG1		69
#define IDC_FLAG2		70
#define IDC_FLAG3		71
#define IDC_FLAG4		72
#define IDC_FLAG5		73
#define IDC_FLAG6		74
#define IDC_FLAG7		75
#define IDC_FLAG8		76
#define IDC_FLAG9		77
#define IDC_FLAG10		78
#define IDC_FLAG11		79
#define IDC_FLAG12		80
#define IDC_FLAG13		81
#define IDC_FLAG14		82
#define IDC_FLAG15		83
#define IDC_FLAG16		84

#define ID_DLG_TOOLS	85
#define IDF_TOOLS		86
#define IDB_APPLY		87
#define IDCB_SOUND		88

// Context Menu
#define MPM_RENAME			200
#define MPM_ADD				201
#define MPM_REMOVE			202
#define MPM_ADD2			203
#define MPM_CLEAR			204

#define MPM_SFX_ADD			211
#define MPM_SFX_REMOVE		212
#define MPM_SFX_PROPERTIES	213
